specUri: github.com/lovethedrake/drakespec
specVersion: v0.6.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: brigadecore/go-tools:v0.1.0
    sourceMountPath: /canard
    workingDirectory: /canard
    tty: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 4096

  baseDindContainer: &baseDindContainer
    name: dind
    image: krancour/dind:18.09.5
    sourceMountPath: /canard
    workingDirectory: /canard
    privileged: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 4096

  baseHelmContainer: &baseHelmContainer
    name: helm
    image: dtzar/helm-kubectl:2.17.0
    sourceMountPath: /canard
    workingDirectory: /canard
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 2048

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  vendor:
    primaryContainer:
      <<: *baseGoContainer
      command: [ "go", "run", "mage.go", "vendor" ]
    sourceMountMode: RW

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "verifyVendor"]
    sourceMountMode: COPY

  test-unit:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "test"]
      sharedStorageMountPath: /shared
    sourceMountMode: COPY

  upload-coverage-report:
    primaryContainer:
      <<: *baseGoContainer
      command: ["bash", "-c"]
      args: ["bash <(curl -s https://codecov.io/bash) -f /shared/coverage.txt"]
      sharedStorageMountPath: /shared

  lint:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "lint"]
    sourceMountMode: COPY

################################################################################
# Build / publish jobs                                                         #
################################################################################

  build-binary:
    primaryContainer:
      <<: *baseGoContainer
      environment:
        CGO_ENABLED: "0"
      command: ["scripts/build-binary.sh"]
      args: ["linux", "amd64"]
      sharedStorageMountPath: /shared

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD variant for use in CI/CD pipelines.
  build-dood:
    primaryContainer:
      <<: *baseDindContainer
      privileged: false
      mountDockerSocket: true
      tty: true
      command: ["scripts/build-dood.sh"]

  build-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-dind.sh"]

  build-and-publish-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-and-publish-dind.sh"]

  publish-binary:
    primaryContainer:
      <<: *baseGoContainer
      command: ["scripts/publish-binary.sh"]
      sharedStorageMountPath: /shared

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-brig
      specVersion: v1.0.0
      config:
        eventTypes:
        - test
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: upload-coverage-report
      dependencies:
      - test-unit
    - name: build-dind
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit

  master:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          branches:
            only:
            - master
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: build-and-publish-dind

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          tags:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    jobs:
    - name: build-binary
    - name: publish-binary
      dependencies:
      - build-binary
    - name: build-and-publish-dind
