specUri: github.com/lovethedrake/drakespec
specVersion: v0.6.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: brigadecore/go-tools:v0.1.0
    sourceMountPath: /brigdrake
    workingDirectory: /brigdrake
    tty: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 4096

  baseDindContainer: &baseDindContainer
    name: dind
    image: krancour/dind:18.09.5
    sourceMountPath: /brigdrake
    workingDirectory: /brigdrake
    privileged: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 4096

  baseHelmContainer: &baseHelmContainer
    name: helm
    image: dtzar/helm-kubectl:2.14.1
    sourceMountPath: /brigdrake
    workingDirectory: /brigdrake
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 2048

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  vendor:
    primaryContainer:
      <<: *baseGoContainer
      command: [ "go", "run", "mage.go", "vendor" ]
    sourceMountMode: RW

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "verifyVendor"]

  test-unit:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "test"]
      args:
      - -timeout
      - 30s
      - -race
      - -coverprofile=/shared/coverage.txt
      - -covermode=atomic
      - ./cmd/...
      - ./pkg/...
      sharedStorageMountPath: /shared

  upload-coverage-report:
    primaryContainer:
      <<: *baseGoContainer
      command: ["bash", "-c"]
      args: ["bash <(curl -s https://codecov.io/bash) -f /shared/coverage.txt"]
      sharedStorageMountPath: /shared

  lint:
    primaryContainer:
      <<: *baseGoContainer
      command: ["golangci-lint", "run"]
      args:
      - ./cmd/...
      - ./pkg/...

  lint-chart:
    primaryContainer:
      <<: *baseHelmContainer
      command: ["helm", "lint"]
      args: ["chart/brigdrake"]

################################################################################
# Build / publish jobs                                                         #
################################################################################

  build-worker-binary:
    primaryContainer:
      <<: *baseGoContainer
      environment:
      - CGO_ENABLED=0
      command: ["scripts/build-worker-binary.sh"]
      args: ["linux", "amd64"]
      sharedStorageMountPath: /shared

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD variant for use in CI/CD pipelines.
  build-worker-dood:
    primaryContainer:
      <<: *baseDindContainer
      privileged: false
      mountDockerSocket: true
      tty: true
      command: ["scripts/build-worker-dood.sh"]

  build-worker-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-worker-dind.sh"]

  build-and-publish-worker-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-and-publish-worker-dind.sh"]

  build-chart:
    primaryContainer:
      <<: *baseHelmContainer
      command: ["scripts/build-chart.sh"]
      sharedStorageMountPath: /shared
    sourceMountMode: COPY

  publish-worker-binary:
    primaryContainer:
      <<: *baseGoContainer
      command: ["scripts/publish-worker-binary.sh"]
      sharedStorageMountPath: /shared

  publish-chart:
    primaryContainer:
      name: node
      image: node:10.16.1
      sourceMountPath: /brigdrake
      workingDirectory: /brigdrake
      command: ["scripts/publish-chart.sh"]
      sharedStorageMountPath: /shared
      resources:
        cpu:
          maxMillicores: 2000
        memory:
          maxMegabytes: 2048
    sourceMountMode: COPY

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-brig
      specVersion: v1.0.0
      config:
        eventTypes:
        - test
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: upload-coverage-report
      dependencies:
      - test-unit
    - name: lint-chart
    - name: build-worker-dind
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart

  master:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          branches:
            only:
            - master
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          tags:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    jobs:
    - name: build-worker-binary
    - name: build-chart
    - name: publish-worker-binary
      dependencies:
      - build-worker-binary
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind
