specUri: github.com/lovethedrake/drakespec
specVersion: v0.2.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: quay.io/deis/lightweight-docker-go:v0.7.0
    sourceMountPath: /go/src/github.com/lovethedrake/brigdrake
    workingDirectory: /go/src/github.com/lovethedrake/brigdrake
    tty: true

  baseDindContainer: &baseDindContainer
    name: dind
    image: krancour/dind:18.09.5
    sourceMountPath: /brigdrake
    workingDirectory: /brigdrake
    privileged: true

  baseHelmContainer: &baseHelmContainer
    name: helm
    image: dtzar/helm-kubectl:2.14.1
    sourceMountPath: /brigdrake
    workingDirectory: /brigdrake

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  dep:
    primaryContainer:
      <<: *baseGoContainer
      command: ["dep", "ensure"]
      args: ["-v"]
    sourceMountMode: RW

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    primaryContainer:
      <<: *baseGoContainer
      command: ["dep", "check"]

  test-unit:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "test"]
      args:
      - -timeout
      - 30s
      - -race
      - -coverprofile=/shared/coverage.txt
      - -covermode=atomic
      - ./cmd/...
      - ./pkg/...
      sharedStorageMountPath: /shared

  upload-coverage-report:
    primaryContainer:
      <<: *baseGoContainer
      command: ["bash", "-c"]
      args: ["bash <(curl -s https://codecov.io/bash) -f /shared/coverage.txt"]
      sharedStorageMountPath: /shared

  lint:
    primaryContainer:
      <<: *baseGoContainer
      command: ["golangci-lint", "run"]
      args:
      - ./cmd/...
      - ./pkg/...

  lint-chart:
    primaryContainer:
      <<: *baseHelmContainer
      command: ["helm", "lint"]
      args: ["chart/brigdrake"]

################################################################################
# Build / publish jobs                                                         #
################################################################################

  # This requires a lot of privilege to run and may be useful locally, but
  # favor the DinD variant for use in CI/CD pipelines.
  build-worker-dood:
    primaryContainer:
      name: dood
      image: krancour/dind:18.09.5
      sourceMountPath: /go/src/github.com/lovethedrake/brigdrake
      workingDirectory: /go/src/github.com/lovethedrake/brigdrake
      mountDockerSocket: true
      tty: true
      command: ["scripts/build-worker-dood.sh"]

  build-worker-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-worker-dind.sh"]

  build-and-publish-worker-dind:
    primaryContainer:
      <<: *baseDindContainer
      command: ["scripts/build-and-publish-worker-dind.sh"]

  build-chart:
    primaryContainer:
      <<: *baseHelmContainer
      command: ["scripts/build-chart.sh"]
      sharedStorageMountPath: /shared
    sourceMountMode: COPY

  publish-chart:
    primaryContainer:
      name: node
      image: node:10.16.1
      sourceMountPath: /brigdrake
      workingDirectory: /brigdrake
      command: ["scripts/publish-chart.sh"]
      sharedStorageMountPath: /shared
    sourceMountMode: COPY

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  test:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: upload-coverage-report
      dependencies:
      - test-unit
    - name: lint-chart
    - name: build-worker-dind
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart

  master:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          branches:
            only:
            - master
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: lint-chart
    - name: build-chart
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
      - lint-chart
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          tags:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    jobs:
    - name: build-chart
    - name: build-and-publish-worker-dind
      dependencies:
      - build-chart
    - name: publish-chart
      dependencies:
      - build-and-publish-worker-dind
