version: 2
jobs:
  test:
    docker:
      - image: brigadecore/go-tools:v0.1.0
    steps:
      - checkout
      - run: go run mage.go -v verifyVendor
      - run: go run mage.go -v test
      - run: bash <(curl -s https://codecov.io/bash)
      - run: go run mage.go -v lint
  publish:
    docker:
      - image: krancour/dind:18.09.5
        user: root
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run: scripts/build-and-publish-dood.sh


workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          context:
            - prod
          filters:
            branches:
              only:
                - master
                - testci
