# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.3
kind: Project
metadata:
  id: hello-world
description: Demonstrates a using drake with brigade
spec:
  workerTemplate:
    container:
      image: "carolynvs/brigdrake-worker:unstable"
      imagePullPolicy: Always
    configFilesDirectory: examples/01-hello-world/.brigade
    git:
      cloneURL: https://github.com/lovethedrake/brigdrake.git
      ref: refs/heads/v2

