#!/bin/sh

set -euo pipefail

export DOCKER_REGISTRY=${DOCKER_REGISTRY:-ghcr.io}
DOCKER_REGISTRY_NAMESPACE=${DOCKER_REGISTRY_NAMESPACE:-lovethedrake}

# Append a trailing slash if set
if [ "$DOCKER_REGISTRY" != "" ]; then
  DOCKER_REGISTRY=$DOCKER_REGISTRY/
fi

if [ "$DOCKER_REGISTRY_NAMESPACE" != "" ]; then
  DOCKER_REGISTRY_NAMESPACE=$DOCKER_REGISTRY_NAMESPACE/
fi

export BASE_IMAGE_NAME=${DOCKER_REGISTRY}${DOCKER_REGISTRY_NAMESPACE}brigdrake-worker
